function plot_mesh_GUI(msh,figfilename)
% PLOT_MESH_GUI   Plot mesh generated by gmsh
% 
% Syntax: plot_mesh_GUI(msh,figfilename) 
% 
% Inputs: 
%    msh - Mesh definitions, structure with fields: 
%    nbNod - number of nodes, integer 
%    POS - coordinates, double, dimensions [nbNod, 3], Units: m 
%    MAX - maximal value of coordinates
%    MIN - minimal value of coordinates
%   QUADS - nodes cooresponding to elements, integer, dimensions [nbElements,5]
%               5th column is for region definition
%   figfilename - name of file for saving figure
% 
% 
% Example: 
%    plot_mesh_GUI(msh,figfilename) 
% 
% Other m-files required: none 
% Subfunctions: none 
% MAT-files required: none 
% See also:
% 

% Author: Pawel Kudela, D.Sc., Ph.D., Eng. 
% Institute of Fluid Flow Machinery Polish Academy of Sciences 
% Mechanics of Intelligent Structures Department 
% email address: pk@imp.gda.pl 
% Website: https://www.imp.gda.pl/en/research-centres/o4/o4z1/people/ 

%---------------------- BEGIN CODE---------------------- 

X=msh.POS(:,1);
Y=msh.POS(:,2);
nRegions = max(msh.QUADS(:,5));
nbElements = size(msh.QUADS,1);
colour = 'rgybmc';
h=figure; hold all;
h.Visible = 'off';
c=1;
for k=1:nRegions
    c1=c;
    while(c <= nbElements && msh.QUADS(c,5)==k)
        c=c+1;
    end 
    nodes = msh.QUADS(c1:c-1,1:4);
    patch('faces',nodes,'vertices',[X Y],'facecolor',colour(k));
end
% size 12cm by 8cm (1-column text)
fig_width = 12; fig_height = 12; 

axis equal;
axis([msh.MIN(1) msh.MAX(1) msh.MIN(2)  msh.MAX(2)]);
set(gca,'FontName','Times');
set(h,'Color','w');
set(gca,'Fontsize',10);
set(h, 'Units','centimeters', 'Position',[10 10 fig_width fig_height]); 
% remove unnecessary white space
set(gca,'LooseInset', max(get(gca,'TightInset'), 0.02));
h.PaperPositionMode   = 'auto';
print(h,figfilename,'-dpng', '-r300'); 
%saveas(h,figfilename,'png');
delete(h);
%---------------------- END OF CODE---------------------- 

% ================ [plot_mesh_GUI.m] ================  
